spring.application.name=team-room-back
#spring.config.import=classpath:secrets.properties
server.address=0.0.0.0
server.port=8080
debug=true
#
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}