package com.example.teamroomback.dtos

data class WebSocketBroadcast(
    val type: WebSocketMessageType,
    val payload: Any
)
enum class WebSocketMessageType {

    JOINED_TO_COURSE,
    REMOVED_FROM_COURSE,
    ROLE_CHANGED_IN_COURSE,
    COURSE_UPDATED,
    COURSE_DELETED,

    MATERIAL_CREATED,
    MATERIAL_UPDATED, // material, media, tags
    MATERIAL_DELETED,

    ASSIGNMENT_CREATED,
    ASSIGNMENT_UPDATED,
    ASSIGNMENT_DELETED,
    ASSIGNMENT_RESPONSE_CREATED,
    ASSIGNMENT_RESPONSE_UPDATED,
    ASSIGNMENT_RESPONSE_DELETED,

    CONFERENCE_STARTED,
    CONFERENCE_PARTICIPANT_LIST_UPDATE,
    CONFERENCE_ENDED,


    USER_MESSAGE,
    REACTION_UPDATE,
    MESSAGE_UPDATE,
    MESSAGE_DELETED,

    START_TYPING,
    STOP_TYPING,

    READ_LAST_MESSAGE,

    SYSTEM_MESSAGE,

    JOINED_TO_CHAT,
    REMOVED_FROM_CHAT,
    ROLE_CHANGED_IN_CHAT,
    CHAT_UPDATED,
    CHAT_DELETED,
}