CREATE TABLE "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" varchar(32) UNIQUE NOT NULL,
    "email" varchar(254) UNIQUE NOT NULL,
    "password_hash" text NOT NULL
);
