CREATE TABLE "profiles" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" int UNIQUE NOT NULL,
    "first_name" varchar(32) NOT NULL,
    "last_name" varchar(32),
    "biography" varchar(100),
    "photo_url" text
);

ALTER TABLE "profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
