CREATE TABLE "rooms" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(512) NOT NULL,
    "photo_url" text
);

CREATE TYPE room_role_type AS ENUM ('MEMBER', 'GUEST', 'ADMIN', 'OWNER');
CREATE TYPE message_type AS ENUM ('JOIN', 'CHAT', 'LEAVE');

CREATE TABLE "room_members" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "room_id" int NOT NULL,
    "user_id" int NOT NULL,
    "role" room_role_type NOT NULL,
    "created_at" timestamp DEFAULT NOW() NOT NULL
);

CREATE TABLE "room_messages" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "room_id" int NOT NULL,
    "sender_id" int NOT NULL,
    "content" text NOT NULL,
    "type" message_type NOT NULL,
    "send_at" timestamp DEFAULT NOW() NOT NULL
);

ALTER TABLE "room_members" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "room_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "room_messages" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "room_messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");
