CREATE TYPE "course_member_role" AS ENUM (
  'OWNER',
  'PROFESSOR',
  'LEADER',
  'STUDENT',
  'VIEWER'
);

CREATE TABLE "courses" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL,
    "photo_url" text,
    "is_open" bool DEFAULT true
);

CREATE TABLE "course_members" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" int NOT NULL,
    "course_id" int NOT NULL,
    "role" "course_member_role" NOT NULL DEFAULT 'STUDENT',
    "created_at" timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE "material_tags" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "material_id" int NOT NULL,
    "name" varchar(20) NOT NULL
);

CREATE TABLE "materials" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "course_id" int NOT NULL,
    "author_id" int NOT NULL,
    "topic" varchar(255) NOT NULL,
    "text_content" text,
    "created_at" timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE "material_media" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "material_id" int NOT NULL,
    "name" varchar(255),
    "file_url" text
);

CREATE TABLE "assignments" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "course_id" int NOT NULL,
    "author_id" int NOT NULL,
    "title" varchar(255) NOT NULL,
    "description" text,
    "max_grade" int DEFAULT 100,
    "created_at" timestamp NOT NULL DEFAULT NOW(),
    "deadline" timestamp NOT NULL
);

CREATE TABLE "assignment_media" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "assignment_id" int NOT NULL,
    "name" varchar(255),
    "file_url" text
);

CREATE TABLE "assignment_responses" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "assignment_id" int NOT NULL,
    "author_id" int NOT NULL,
    "is_returned" bool DEFAULT false,
    "return_comment" text,
    "is_graded" bool DEFAULT false,
    "grade" int,
    "grade_comment" text
);

CREATE TABLE "assignment_response_media" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "assignment_response_id" int NOT NULL,
    "name" varchar(255),
    "file_url" text
);


ALTER TABLE "course_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "course_members" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "material_tags" ADD FOREIGN KEY ("material_id") REFERENCES "materials" ("id");

ALTER TABLE "materials" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "materials" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id");

ALTER TABLE "material_media" ADD FOREIGN KEY ("material_id") REFERENCES "materials" ("id");

ALTER TABLE "assignments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "assignments" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id");

ALTER TABLE "assignment_media" ADD FOREIGN KEY ("assignment_id") REFERENCES "assignments" ("id");

ALTER TABLE "assignment_responses" ADD FOREIGN KEY ("assignment_id") REFERENCES "assignments" ("id");

ALTER TABLE "assignment_responses" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id");

ALTER TABLE "assignment_response_media" ADD FOREIGN KEY ("assignment_response_id") REFERENCES "assignment_responses" ("id");