
CREATE TYPE chat_type AS ENUM (
  'PRIVATE',
  'GROUP',
  'MAIN_COURSE_CHAT',
  'COURSE_CHAT'
);

CREATE TYPE chat_member_role AS ENUM (
  'OWNER',
  'ADMIN',
  'MODERATOR',
  'MEMBER',
  'VIEWER'
);

CREATE TYPE chat_message_type AS ENUM (
  'USER_JOINED_TO_CHAT',
  'USER_LEFT_FROM_CHAT',
  'USER_MESSAGE',
  'COURSE_OPENED',
  'COURSE_CLOSED',
  'MATERIAL_CREATED',
  'MATERIAL_UPDATED',
  'MATERIAL_DELETED',
  'ASSIGNMENT_CREATED',
  'ASSIGNMENT_UPDATED',
  'ASSIGNMENT_DELETED',
  'ASSIGNMENT_DEADLINE_IN_24HR',
  'ASSIGNMENT_DEADLINE_ENDED',
  'CONFERENCE_STARTED',
  'CONFERENCE_ENDED'
);

CREATE TYPE chat_message_related_entity_type AS ENUM (
  'MATERIAL',
  'ASSIGNMENT',
  'CONFERENCE'
);


CREATE TABLE chats (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    photo_url TEXT,
    type chat_type NOT NULL,
    course_id INT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE chat_messages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    user_id INT,
    content TEXT,
    type chat_message_type NOT NULL DEFAULT 'USER_MESSAGE',
    reply_to_message INT,
    sent_at TIMESTAMP NOT NULL DEFAULT NOW(),
    edited_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE chat_member (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    user_id INT NOT NULL,
    role chat_member_role NOT NULL DEFAULT 'MEMBER',
    last_accessible_message_id INT REFERENCES chat_messages(id),
    joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
    last_read_message_id INT REFERENCES chat_messages(id),
    last_read_at TIMESTAMP,
    CONSTRAINT chat_member_chat_user_key UNIQUE (chat_id, user_id)
);

CREATE TABLE chat_message_related_entity (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    related_entity_type chat_message_related_entity_type NOT NULL,
    related_entity_id INT NOT NULL,
    CONSTRAINT msg_related_entity_key UNIQUE (message_id, related_entity_type, related_entity_id)
);

CREATE TABLE chat_message_media (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    file_name VARCHAR(255),
    file_type VARCHAR(100),
    file_size_bytes INT
);

CREATE TABLE message_reactions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    user_id INT NOT NULL,
    reaction_emoji VARCHAR(10) NOT NULL,
    reaction_time TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT msg_user_reaction_key UNIQUE (message_id, user_id, reaction_emoji)
);

CREATE TABLE pinned_messages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    message_id INT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    pinned_by_user_id INT NOT NULL,
    pinned_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT chat_pinned_message_key UNIQUE (chat_id, message_id)
);

ALTER TABLE chat_messages
ADD CONSTRAINT fk_reply_to_message
FOREIGN KEY (reply_to_message) REFERENCES chat_messages(id)
ON DELETE SET NULL;

CREATE INDEX idx_chat_messages_chat_id ON chat_messages(chat_id);

CREATE INDEX idx_chat_message_media_message_id ON chat_message_media(message_id);

CREATE UNIQUE INDEX idx_chats_unique_main_course_chat
ON chats (course_id)
WHERE type = 'MAIN_COURSE_CHAT';

ALTER TABLE chats
ADD CONSTRAINT fk_chats_course_id
FOREIGN KEY (course_id) REFERENCES courses(id)
ON DELETE CASCADE;

ALTER TABLE chat_messages
ADD CONSTRAINT fk_chat_messages_user_id
FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE SET NULL;

ALTER TABLE chat_member
ADD CONSTRAINT fk_chat_member_user_id
FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE CASCADE;

ALTER TABLE message_reactions
ADD CONSTRAINT fk_message_reactions_user_id
FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE CASCADE;

ALTER TABLE pinned_messages
ADD CONSTRAINT fk_pinned_messages_user_id
FOREIGN KEY (pinned_by_user_id) REFERENCES users(id)
ON DELETE SET NULL;



DROP TABLE IF EXISTS room_messages CASCADE;
DROP TABLE IF EXISTS room_members CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TYPE IF EXISTS message_type CASCADE;
DROP TYPE IF EXISTS room_role_type CASCADE;