DROP TYPE IF EXISTS conference_status CASCADE;
DROP TYPE IF EXISTS conference_participant_role CASCADE;
DROP TABLE IF EXISTS conference_participants CASCADE;
DROP TABLE IF EXISTS conferences CASCADE;

CREATE TYPE conference_status AS ENUM (
  'ACTIVE',
  'ENDED'
);

CREATE TYPE conference_participant_role AS ENUM (
  'MODERATOR',
  'MEMBER',
  'VIEWER'
);

CREATE TABLE conferences (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  subject TEXT,
  room_name VARCHAR(255) NOT NULL UNIQUE,
  status conference_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMP
);

CREATE TABLE conference_participants (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  conference_id INTEGER NOT NULL REFERENCES conferences(id) ON DELETE CASCADE,
  role conference_participant_role NOT NULL DEFAULT 'MEMBER',
  joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
  left_at TIMESTAMP
);

CREATE INDEX idx_conferences_course_id ON conferences(course_id);
CREATE INDEX idx_conference_participants_user_id ON conference_participants(user_id);
CREATE INDEX idx_conference_participants_conference_id ON conference_participants(conference_id);